### ISSUE TITLE
Rewrite Docs for newer codebase

### ISSUE THREAD

**Issue by SujalChoudhari** [SujalChoudhari/Neptune.js#8]
New Entity-Component based system is in development.
Docs for the newer codebase should move to a different repository.

**Comment by Ansh-code398** [comment]
Aren't you working with jsdoc anymore?

**Comment by SujalChoudhari** [comment]
> Aren't you working with jsdoc anymore?

Actually, I changed my mind. Docs will be in same repository for easy access and embedding.
The Documentations are being re-written with jsdoc.
Take a look at [entity-component](https://github.com/SujalChoudhari/Neptune.js/tree/entity-component) branch.

**Comment by SujalChoudhari** [comment]
Documentation Completed.
